{
    'name': 'Document Management',
    'version': '13.0.1.0.0',
    'summary': 'Module for managing documents and books',
    'sequence': 10,
    'description': """This module allows to manage documents""",
    'category': 'Document Management',
    'author': 'Your Name',
    'website': '',
    'depends': ['base', 'hr'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/document_views.xml',
        'wizards/document_report_wizard.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}